<a href="https://colab.research.google.com/github/sagebanks/Data-Science/blob/main/Sage_Banks_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [29]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


ir prints 10 diffeent numbers depeding on what you put in the ()

In [30]:
for i in range(5,8):
    print(i)

5
6
7


it prined numbers between 5 and 8

In [31]:
for i in range(5):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2
Test Number:  3
Test Number:  4


it printed the word Test Number (5) times because thats what was in the ()

### Functions

In [32]:
def square(x):
    return x**2

the word square is now defined at squaring numbers

In [33]:
square(5)

25

its squaring (5) into 25

In [34]:
square(square(2))

16

In [35]:
square(square(square(2)))


256

In [36]:
square(123456)

15241383936

In [37]:
square(square(5))

625

In [38]:
def add_two(x):
    return x+2

In [39]:
add_two(5)

7

In [40]:
square(add_two(5))

49

### Logical Branching

In [41]:
choice = "apple"

you chose apple

In [42]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


if you picked apples it will print "you choose apples" but if you didnt it will say you did not choose apples

In [43]:
choice = "orange"

you chose orange

In [44]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [45]:
choice = "apple"

In [46]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


if yo pick apples or oranges it will say you choose apples or you choose oranges it will also tell you thank you, shop again

### User Input

In [94]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): 


put imput to get it to say word like please enter your choice

In [95]:
choice

''

In [96]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


it printed you choose apples because apples was the choice made earlier

#### Coins

In [97]:
import numpy as np

needed to import numpy as np

In [98]:
np.random.random()

0.6294014462689945

np chose a random number

In [99]:
np.random.random() > 0.5

True

if the random number is biger than 0.5 then its considerred true

In [100]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

when flipping the coin any number bigger then 0.5 is heads and any number less is tails

In [101]:
flip_coin()

Heads


### Graphics Output

In [102]:
from IPython.core.display import display, HTML

In [103]:
display(HTML('<h1>Hello, world!</h1>'))

its displaying hello, world 

In [104]:
def coin():
  return np.random.randint(2)

it picks a number from 1 to 2

In [105]:

coin()

0

In [106]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

it will display the image of the link provided

In [107]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

it is the links for heads and tails quarter coins

In [108]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [109]:
show_img(heads)

In [110]:
show_img(tails)

In [111]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

when the coin is flipped it will show either heads or tails

In [112]:
flip_coin()

In [113]:
for i in range(5):
    flip_coin()

In [114]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [115]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [116]:
a = np.arange(52)

it an arange of 52 meaning all 52 cards in a deck

In [117]:
shuffle(a)

array([32, 27, 39, 36, 49, 38, 26,  3, 45,  9, 18, 44, 10, 12,  1, 11, 48,
       29, 46, 28, 35, 37, 41, 20,  4, 47, 42, 34,  7,  0,  5,  8, 19, 30,
        6, 43, 15, 23, 13, 31, 22, 24, 17, 16, 51, 33, 21,  2, 40, 50, 25,
       14])

In [118]:
np.random.permutation(52)

array([13, 26, 16,  8,  9, 49, 32, 23, 33,  2, 47, 48, 50, 43, 38,  7,  1,
        6, 14, 25, 20,  0, 35, 42, 36, 10, 51, 46, 11, 44,  5,  3, 40, 19,
       37, 29,  4, 24, 28, 39, 41, 12, 21, 15, 18, 30, 27, 17, 31, 34, 45,
       22])

### Speed Test

In [119]:
%%timeit
shuffle(a)

185 µs ± 7.79 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [120]:
%%timeit
np.random.permutation(52)

3.8 µs ± 416 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [121]:
import numpy as np

In [122]:
np.random.permutation(52)

array([47, 51,  6, 44, 43, 16,  7, 15,  2, 13,  4, 10, 50, 17, 39,  9,  1,
        8, 11, 28, 23, 48, 38, 14,  5, 40, 35, 49, 26, 41, 33, 37,  3, 46,
       22, 24, 30, 27,  0, 36, 20, 31, 45, 18, 21, 25, 32, 19, 29, 34, 12,
       42])

it gave an array of 52 numbers

In [123]:
cards = np.random.permutation(52)

defining that cards will provide the array of numbers from before

In [124]:
cards

array([46, 20, 45,  2,  4, 16, 15, 42, 14,  7, 40, 11, 13, 21,  9,  0, 28,
       49, 48, 39, 10, 24, 12,  8, 38, 32, 33,  1,  5, 31, 23, 18, 37, 27,
       22,  3, 35, 41, 34, 19, 17, 26, 51, 44, 30,  6, 50, 29, 43, 47, 36,
       25])

In [125]:
cards[0]

46

[0] pick the 0 number from the array and displays it

In [126]:
cards[1]

20

In [127]:
cards[2]

45

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

imported link of pictures

In [128]:











np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

displayed the array but in 4 rowns and 13 columns

In [156]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

its displaying the same as before but only number till 13

In [130]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [131]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

defining the suits and names of the cards

In [157]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [133]:
card_name(0)

'Ace of Clubs'

In [134]:
card_name(51)

'King of Diamonds'

In [135]:
cards = np.random.permutation(52)

In [136]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [137]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Ace of Spades', 'Eight of Diamonds', 'Eight of Spades')

In [138]:
for i in range(5):
    print(card_name(cards[i]))

Ace of Spades
Eight of Diamonds
Five of Spades
Jack of Spades
Six of Hearts


it printed 5 card names

In [139]:
for i in range(15):
    print(card_name(cards[i]))

Ace of Spades
Eight of Diamonds
Five of Spades
Jack of Spades
Six of Hearts
Five of Hearts
Queen of Clubs
Three of Clubs
Five of Clubs
Jack of Hearts
Three of Hearts
Five of Diamonds
Two of Spades
Seven of Spades
Ten of Hearts


it printed 15 card names 

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [140]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [141]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [142]:
i = np.random.randint(4)
j = np.random.randint(13)

In [143]:
i,j

(3, 8)

In [144]:
suit[i]

'l'

In [145]:
card[j]

'9'

In [146]:
from IPython.core.display import display, HTML

In [147]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [148]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [149]:
show_img(img)

In [150]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [151]:
card_image(3)

'k4'

In [152]:
img = card_url_head + card_image(3) + card_url_tail

In [153]:
show_img(img)

In [154]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)